version: "3.3"

services:
  blacksea:
    build:
      context: ./blacksea
      dockerfile: Dockerfile
    container_name: blacksea
    networks:
      - backend

  # nginx:
  #   image: nginx:latest
  #   container_name: blacksea_nginx
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #   networks:
  #     - backend
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: HKHackerForum
      MYSQL_DATABASE: hackerforum
    networks:
      - backend

networks:
  backend:
  frontend:
